version: "3.8"

services:
  x-cosmos-mcp-app:
    build: .
    command: bash -c "python -c 'import time; time.sleep(10)' && python pipeline.py --task meta"
    volumes:
      - .:/app
    network_mode: "host"
    environment:
      - OLLAMA_HOST=http://localhost:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - x-cosmos-msp-api

  x-cosmos-msp-api:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    network_mode: "host"
    environment:
      - OLLAMA_HOST=http://localhost:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 100s
      retries: 3
      start_period: 10s
