services:
  x-backend:
    build: .
    volumes:
      - .:/app
    depends_on:
      - ollama

  x-cosmos-mcp-app:
    extends:
      service: x-backend
    command: bash -c "python -c 'import time; time.sleep(10)' && python app/pipeline.py --task meta"

  x-cosmos-msp-api:
    extends:
      service: x-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 100s
      retries: 3
      start_period: 10s

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama.models:/root/.ollama
