#!/usr/bin/env python3
"""
orchestrator-v6.py

Orchestrator wrapper that runs analyzer then normalizer (or either).
This version is tolerant of differing method signatures:
- It tries the newer streaming signatures (max_files, show_progress, process_all_stream)
  and falls back to older signatures (max_products, batch_size, process_all) when needed.

Usage examples:
  python orchestrator-v6.py --analyze --normalize --workers 2
  python orchestrator-v6.py --analyze
  python orchestrator-v6.py --normalize --tag-csv path/to/tag.csv --type-csv path/to/type.csv
"""

import argparse
import logging
from pathlib import Path
from datetime import datetime
from logging.handlers import TimedRotatingFileHandler

# Local module imports - ensure these files are in same folder or on PYTHONPATH
try:
    from optimus_v4 import ProductAnalyzer
    from optimus_v4_normalizer import ProductNormalizer
except Exception as e:
    print(f"Failed to import modules: {e}")
    raise


# ---------- basic logging for orchestrator ----------
def setup_orch_logger(log_dir: Path):
    logger = logging.getLogger("orchestrator")
    logger.setLevel(logging.INFO)
    if logger.handlers:
        return logger
    fmt = logging.Formatter(
        "%(asctime)s %(levelname)s: %(message)s", "%Y-%m-%dT%H:%M:%S%z"
    )
    ch = logging.StreamHandler()
    ch.setFormatter(fmt)
    logger.addHandler(ch)
    log_dir.mkdir(parents=True, exist_ok=True)
    fh = TimedRotatingFileHandler(
        str(log_dir / f"orchestrator_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"),
        when="midnight",
        backupCount=7,
    )
    fh.setFormatter(fmt)
    logger.addHandler(fh)
    return logger


# ---------- small HTML report functions ----------
def link_or_path(v):
    if not v:
        return "—"
    p = Path(v)
    if p.exists():
        # return relative link text
        return f'<a href="{p.as_posix()}">{p.name}</a>'
    return f"{v}"


def generate_html_report(report_path: Path, data: dict):
    report_path.parent.mkdir(parents=True, exist_ok=True)
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Pipeline run report - {data.get('run_id')}</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <style>
    body{{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial; margin:24px; color:#111}}
    h1{{font-size:20px; margin-bottom:8px}}
    .box{{border:1px solid #eee; padding:12px; margin:12px 0; border-radius:8px; background:#fafafa}}
    .k{{font-weight:600;color:#0b5fff;}}
    a{{color:#0b5fff; text-decoration:none}}
    table{{width:100%; border-collapse:collapse; margin-top:10px}}
    td,th{{padding:8px; border-bottom:1px solid #f1f1f1; text-align:left}}
    .muted{{color:#666; font-size:13px}}
  </style>
</head>
<body>
  <h1>Pipeline run report</h1>
  <div class="muted">run id: <span class="k">{data.get('run_id')}</span> &nbsp; • &nbsp; started: {data.get('start_time')} &nbsp; • &nbsp; ended: {data.get('end_time')}</div>

  <div class="box">
    <h2>Analyzer</h2>
    <table>
      <tr><th>Files processed</th><td>{data.get('analyzer', {}).get('total_files', '—')}</td></tr>
      <tr><th>Products seen</th><td>{data.get('analyzer', {}).get('total_products', '—')}</td></tr>
      <tr><th>Tag CSV</th><td>{link_or_path(data.get('analyzer', {}).get('tag_csv'))}</td></tr>
      <tr><th>Type CSV</th><td>{link_or_path(data.get('analyzer', {}).get('type_csv'))}</td></tr>
      <tr><th>Log</th><td>{link_or_path(data.get('analyzer', {}).get('log_file'))}</td></tr>
    </table>
  </div>

  <div class="box">
    <h2>Normalizer</h2>
    <table>
      <tr><th>Files processed</th><td>{data.get('normalizer', {}).get('total_files', '—')}</td></tr>
      <tr><th>Products normalized</th><td>{data.get('normalizer', {}).get('total_products', '—')}</td></tr>
      <tr><th>Normalized output</th><td>{link_or_path(data.get('normalizer', {}).get('output_dir'))}</td></tr>
      <tr><th>Log</th><td>{link_or_path(data.get('normalizer', {}).get('log_file'))}</td></tr>
    </table>
  </div>

  <div class="box">
    <h2>Notes</h2>
    <div class="muted">{data.get('notes', '')}</div>
  </div>

  <footer class="muted">Generated by orchestrator-v6.py</footer>
</body>
</html>"""
    report_path.write_text(html, encoding="utf-8")


# ---------- main ----------
def main():
    parser = argparse.ArgumentParser(
        description="Orchestrate analysis + normalization pipeline (v6)"
    )
    parser.add_argument("--analyze", action="store_true")
    parser.add_argument("--normalize", action="store_true")
    parser.add_argument("--input-folder", default="data/json/products_by_id")
    parser.add_argument("--analysis-output", default="analysis_output")
    parser.add_argument("--normalized-output", default="normalized_output")
    parser.add_argument(
        "--max-files", type=int, help="Limit number of gz files to process (streaming)"
    )
    parser.add_argument("--analyzer-batch-size", type=int, default=50)
    parser.add_argument(
        "--workers", type=int, default=4, help="Number of threads for normalizer"
    )
    parser.add_argument("--no-progress", action="store_true")
    parser.add_argument(
        "--tag-csv", help="If provided, skip analyzer -> use this tag CSV"
    )
    parser.add_argument(
        "--type-csv", help="If provided, skip analyzer -> use this type CSV"
    )
    parser.add_argument(
        "--report-dir", default="reports", help="Where to save HTML reports"
    )

    args = parser.parse_args()

    log_dir = Path("logs")
    logger = setup_orch_logger(log_dir)

    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    start_time = datetime.now().isoformat()

    tag_csv = args.tag_csv
    type_csv = args.type_csv

    analyzer_info = {}
    normalizer_info = {}

    # ---------- ANALYZER ----------
    if args.analyze:
        logger.info("Starting analyzer...")
        analyzer = ProductAnalyzer(
            input_folder=args.input_folder,
            output_dir=args.analysis_output,
        )

        # Try the streaming signature first; fall back to older signature if necessary.
        try:
            analyzer_res = analyzer.run_analysis(
                max_files=args.max_files, show_progress=not args.no_progress
            )
        except TypeError:
            logger.info(
                "Analyzer.run_analysis signature mismatch — falling back to older signature names."
            )
            # older implementations used: run_analysis(source="disk", max_products=..., batch_size=...)
            try:
                analyzer_res = analyzer.run_analysis(
                    source="disk",
                    max_products=args.max_files,
                    batch_size=args.analyzer_batch_size,
                )
            except Exception as e:
                logger.error(f"Analyzer fallback failed: {e}")
                raise

        # normalize analyzer result keys
        tag_csv = analyzer_res.get("tag_csv") or tag_csv
        type_csv = analyzer_res.get("type_csv") or type_csv

        # try to discover analyzer log
        analyzer_log = None
        ao = Path(args.analysis_output)
        if ao.exists():
            logs = sorted(ao.glob("optimus_v4_analyzer_*.log"), reverse=True)
            if logs:
                analyzer_log = str(logs[0])

        analyzer_info = {
            "total_files": analyzer_res.get("total_files"),
            "total_products": analyzer_res.get("total_products"),
            "tag_csv": tag_csv,
            "type_csv": type_csv,
            "log_file": analyzer_log,
        }
        logger.info(f"Analyzer finished. tag_csv={tag_csv} type_csv={type_csv}")

    # ---------- NORMALIZER ----------
    if args.normalize:
        # ensure we have CSVs
        if not tag_csv or not type_csv:
            ap = Path(args.analysis_output)
            if ap.exists():
                tag_matches = sorted(ap.glob("tag_analysis_*.csv"), reverse=True)
                type_matches = sorted(ap.glob("type_analysis_*.csv"), reverse=True)
                if tag_matches and not tag_csv:
                    tag_csv = str(tag_matches[0])
                if type_matches and not type_csv:
                    type_csv = str(type_matches[0])

        if not tag_csv or not type_csv:
            logger.error(
                "Tag or Type CSV not found. Run analyzer first or provide --tag-csv and --type-csv."
            )
            return

        logger.info("Starting normalizer...")
        normalizer = ProductNormalizer(
            output_dir=args.normalized_output,
            input_folder=args.input_folder,
        )

        # Try the streaming multithreaded signature first; fall back to process_all older signature.
        try:
            norm_res = normalizer.process_all_stream(
                tag_csv=tag_csv,
                type_csv=type_csv,
                input_folder=args.input_folder,
                workers=args.workers,
                max_files=args.max_files,
                update_supabase=False,
                show_progress=not args.no_progress,
            )
        except TypeError:
            logger.info(
                "Normalizer.process_all_stream signature missing — falling back to older process_all."
            )
            try:
                # older signature: process_all(tag_csv, type_csv, max_products=..., batch_size=..., update_supabase=...)
                norm_res = normalizer.process_all(
                    tag_csv=tag_csv,
                    type_csv=type_csv,
                    source="disk",
                    input_folder=args.input_folder,
                    max_products=args.max_files,
                    batch_size=args.analyzer_batch_size,
                    update_supabase=False,
                )
            except Exception as e:
                logger.error(f"Normalizer fallback failed: {e}")
                raise

        # discover normalizer log
        normalizer_log = None
        no = Path(args.normalized_output)
        if no.exists():
            logs = sorted(no.glob("optimus_v4_normalizer_*.log"), reverse=True)
            if logs:
                normalizer_log = str(logs[0])

        normalizer_info = {
            "total_files": norm_res.get("total_files"),
            "total_products": norm_res.get("total_products"),
            "output_dir": str(Path(args.normalized_output).resolve()),
            "log_file": normalizer_log,
        }
        logger.info(
            f"Normalizer finished. files={normalizer_info.get('total_files')} products={normalizer_info.get('total_products')}"
        )

    if not args.analyze and not args.normalize:
        logger.info("Nothing to run. Use --analyze and/or --normalize.")
        return

    # ---------- HTML report ----------
    end_time = datetime.now().isoformat()
    report_dir = Path(args.report_dir)
    report_dir.mkdir(parents=True, exist_ok=True)
    report_file = report_dir / f"run_report_{run_id}.html"
    report_data = {
        "run_id": run_id,
        "start_time": start_time,
        "end_time": end_time,
        "analyzer": analyzer_info,
        "normalizer": normalizer_info,
        "notes": "Run generated by orchestrator-v6.py (compat fallback enabled).",
    }
    generate_html_report(report_file, report_data)
    logger.info(f"HTML report written to: {report_file}")


if __name__ == "__main__":
    main()
